on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up apt sources
        run: sudo sed -i 's/azure\./nl\./' /etc/apt/sources.list

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}

      - name: Install a specific versions of dplyr and readr
        run: devtools::install_version("dplyr", version = "1.0.9"); devtools::install_version("readr", version = "2.1.2"); devtools::install_version("tidyr", version="1.2.1");
        shell: Rscript {0}
        
      - name: Install a specific version of ggplot2
        run: devtools::install_version("ggplot2", version = "3.4.0"); 
        shell: Rscript {0}
        
      - name: Install a specific version of igraph
        run: devtools::install_version("igraph", version = "1.3.5"); 
        shell: Rscript {0}

      - name: Install vimure
        run: devtools::install_github("latentnetworks/vimure", subdir="src/R", ref="develop");vimure::install_vimure()
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: docs
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
