on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - docs/**

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up apt sources
        run: sudo sed -i 's/azure\./nl\./' /etc/apt/sources.list

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install rmarkdown
        run: install.packages("rmarkdown");
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: docs
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
